//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDataLib.DataComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        public int PatientID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal Amount { get; set; }
    }
}
